[project]
name = "intro-to-prefect"
description = "An introductory project to Prefect"
version = "0.1.0"
authors = [
    { name = "michael \"alex\" basweti", email = "baswetima@gmail.com" }
]
dependencies = [
    "prefect>=3.0",
    "httpx~=0.28",
    "psycopg2-binary~=2.9.10"
]

[project.optional-dependencies]
dev = [
    "pre-commit"
]

[project.scripts]
pipeline = "pipeline.main:main"
